### ISSUE TITLE
where is the zero downtime api?

### ISSUE THREAD

**Issue by huowa222** [facebook/mvfst#262]
where is the zero downtime api?

**Comment by huowa222** [comment]
I'm looking for zero downtime API which is illustrated in README. keep old server working when trigger reload i mean.

**Comment by afrind** [comment]
Aha, this one:

> APIs to enable zero-downtime restarts of servers, so that applications do not have to drop connections when restarting.

The APIs are here: 

https://github.com/facebookincubator/mvfst/blob/main/quic/server/QuicServer.h#L257-L312

Though I admit, an example of how to use these APIs is lacking.  I'll see if I can update this with an example of how to execute a socket takeover.  The general idea is that the socket FD gets passed from the old server process to the new one, and any packets received in the new process which belong to connections in the old process are forwarded there.

**Comment by huowa222** [comment]
domain sockets for muti-processes communication.

**Comment by afrind** [comment]
I never got around to adding an example here, but maybe interest has also waned.  Closing for now.
