### ISSUE TITLE
Does mvfst support RFC 9221?

### ISSUE THREAD

**Issue by HaseebLUMS** [facebook/mvfst#313]
I am interested in the datagrams sharing congestion state with streams feature of RFC 9221. Please let me know if this is not the platform to ask this question.

**Comment by afrind** [comment]
Yes, here are the datagram APIs in QuicSocket: https://github.com/facebook/mvfst/blob/main/quic/api/QuicSocket.h#L1402

You'll need to enable it via TransportSetting's https://github.com/facebook/mvfst/blob/main/quic/state/TransportSettings.h#L247
